# Generated by Django 5.1.3 on 2024-11-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_name', models.CharField(max_length=120)),
                ('data', models.JSONField(default=None, null=True)),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
            ],
            options={
                'verbose_name': 'Игрок',
                'verbose_name_plural': 'Игроки',
                'indexes': [models.Index(fields=['-tg_name', 'create'], name='state_state_tg_name_916271_idx')],
            },
        ),
    ]
