# Generated by Django 5.1.3 on 2024-11-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='state',
            name='state_state_tg_name_916271_idx',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='create',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='update',
            new_name='updated',
        ),
        migrations.AlterField(
            model_name='state',
            name='tg_name',
            field=models.SlugField(),
        ),
        migrations.AddIndex(
            model_name='state',
            index=models.Index(fields=['-tg_name', 'created'], name='state_state_tg_name_f96873_idx'),
        ),
    ]
